CREATE DATABASE IF NOT EXISTS V1GS5D;

USE V1GS5D;

CREATE TABLE IF NOT EXISTS Termekek_Es_Szolgaltatasok(
ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
Nev varchar(100) NOT NULL,
Tipus BOOLEAN NOT NULL,
Keszleten INT UNSIGNED NOT NULL,
Ar INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Vevok (
VevoID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
VevoNev varchar(100) NOT NULL,
Vett_termekek varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS beszallitok (
beszallitoID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
beszallitoNev varchar(100) NOT NULL,
Termek_Es_Szolgaltatas_ID INT UNSIGNED NOT NULL,
FOREIGN KEY (Termek_Es_Szolgaltatas_ID) REFERENCES Termekek_Es_Szolgaltatasok(ID),
Ar INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Szamla (
ID INT UNSIGNED PRIMARY KEY NOT NULL,
VevoID INT UNSIGNED NOT NULL,
Termek_Es_Szolgaltatas_ID INT UNSIGNED NOT NULL,
FOREIGN KEY (VevoID) REFERENCES Vevok(VevoID),
FOREIGN KEY (Termek_Es_Szolgaltatas_ID) REFERENCES Termekek_Es_Szolgaltatasok(ID),
ArOsszeg DOUBLE NOT NULL,
Kelte DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS bevetelezes (
bevetelezesID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
VevoID INT UNSIGNED NOT NULL,
kiszamlazott_osszeg INT UNSIGNED NOT NULL,
FOREIGN KEY (VevoID) REFERENCES Vevok(VevoID),
FOREIGN KEY (kiszamlazott_osszeg) REFERENCES Szamla(ID)
);

